const actionTypes = Object.freeze({
     //app
     APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
     SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
     CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
     //user
     ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
     USER_LOGIN_SUCCESS: 'ADD_USER_SUCCESS',
     USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
     PROCESS_LOGOUT: 'PROCESS_LOGOUT',
     //admin director
     GET_PENDING_USER: 'GET_PENDING_USER',
     GET_PENDING_USER_SUCCESS: 'GET_PENDING_USER_SUCCESS',
     CREATE_UPDATE_USER_PENDING_SUCCESS: 'CREATE_UPDATE_USER_PENDING_SUCCESS',
     CREATE_UPDATE_USER_PENDING_FAILED: 'CREATE_UPDATE_USER_PENDING_FAILED',
     IS_EDIT_ADMIN_PENDING: 'IS_EDIT_ADMIN_PENDING',
     IS_NOT_EDIT_ADMIN_PENDING: 'IS_NOT_EDIT_ADMIN_PENDING',
     FETCH_DATA_EDIT_ADMIN_PENDING: 'FETCH_DATA_EDIT_ADMIN_PENDING',
     CLEAR_DATA_EDIT_ADMIN_PENDING: 'CLEAR_DATA_EDIT_ADMIN_PENDING',
     /*transaction */
     GET_ALL_TRANSACTIONS: 'GET_ALL_TRANSACTIONS',
     GET_ALL_TRANSACTIONS_SUCCESS: 'GET_ALL_TRANSACTIONS',
     GET_ALL_TRANSACTIONS_FAILED: 'GET_ALL_TRANSACTIONS',
     GET_ALL_ADMIN_TRANSACTIONS_SUCCESS: 'GET_ALL_ADMIN_TRANSACTIONS',
     GET_ALL_ADMIN_TRANSACTIONS_FAILED: 'GET_ALL_ADMIN_TRANSACTIONS',
     IS_EDIT_TRANSACTION: 'IS_EDIT_TRANSACTION',
     IS_NOT_EDIT_TRANSACTION: 'IS_NOT_EDIT_TRANSACTION',
     FETCH_DATA_EDIT_TRANSACTION: 'FETCH_DATA_EDIT_TRANSACTION',
     CLEAR_DATA_EDIT_TRANSACTION: 'CLEAR_DATA_EDIT_TRANSACTION',
     /*collection */
     GET_ALL_COLLECTIONS: 'GET_ALL_COLLECTIONS',
     GET_ALL_COLLECTIONS_SUCCESS: 'GET_ALL_COLLECTIONS_SUCCESS',
     GET_ALL_COLLECTIONS_FAILED: 'GET_ALL_COLLECTIONS_FAILED',
     GET_ALL_ADMIN_COLLECTIONS_SUCCESS: 'GET_ALL_ADMIN_COLLECTIONS_SUCCESS',
     GET_ALL_ADMIN_COLLECTIONS_FAILED: 'GET_ALL_ADMIN_COLLECTIONS_FAILED',
     IS_EDIT_COLLECTION: 'IS_EDIT_COLLECTION',
     IS_NOT_EDIT_COLLECTION: 'IS_NOT_EDIT_COLLECTION',
     FETCH_DATA_EDIT_COLLECTION: 'FETCH_DATA_EDIT_COLLECTION',
     CLEAR_DATA_EDIT_COLLECTION: 'CLEAR_DATA_EDIT_COLLECTION',
     //==================================================================
     //*transaction admin action */
     GET_ALL_TRANSACTION_BY_ID_SUCCESS: 'GET_ALL_TRANSACTION_BY_ID_SUCCESS',
     GET_ALL_TRANSACTION_BY_ID_FAILED: 'GET_ALL_TRANSACTION_BY_ID_FAILED',
     FETCH_DATA_EDIT_STAFF_SUCCESS: 'FETCH_DATA_EDIT_STAFF_SUCCESS',
     FETCH_DATA_EDIT_STAFF_FAILED: 'FETCH_DATA_EDIT_STAFF_FAILED',
     IS_EDIT_STAFF: 'IS_EDIT_STAFF',
     IS_NOT_EDIT_STAFF: 'IS_NOT_EDIT_STAFF',
     //*collection admin action */
     GET_ALL_TRANSACTION_STAFF_BY_ID_SUCCESS: 'GET_ALL_TRANSACTION_STAFF_BY_ID_SUCCESS',
     GET_ALL_TRANSACTION_STAFF_BY_ID_FAILED: 'GET_ALL_TRANSACTION_STAFF_BY_ID_FAILED',
     //get all parcel pending
     GET_ALL_PENDING_PARCEL_SUCCESS: 'GET_ALL_PENDING_PARCEL_SUCCESS',
     GET_ALL_PENDING_PARCEL_FAILED: 'GET_ALL_PENDING_PARCEL_FAILED',
});
export default actionTypes;
